Output demo_manual.gif

  Set FontFamily "Geist Mono"
  Set TypingSpeed 133ms
  Set FontSize 28
  Set Width 1200
  Set Height 600

  Sleep 500ms
  Type "dstimer"
  Sleep 1s
  Enter
  Sleep 1500ms
  Type "0"
  Sleep 300ms
  Type "0"
  Sleep 300ms
  Type "0"
  Sleep 300ms
  Type "0"
  Sleep 300ms
  Type "0"
  Sleep 300ms
  Type "7"
  Sleep 1s
  Enter
  Sleep 1s

  Set TypingSpeed 77ms

  Type "/home/linuxg/Musik/Super Survivor.flac"
  Sleep 1s
  Enter
  Sleep 1s
  Enter
  Sleep 9s
