Output demo_inline_manual.gif

  Set FontFamily "Geist Mono"
  Set TypingSpeed 100ms
  Set FontSize 24
  Set Width 1200
  Set Height 400

  Sleep 500ms
  Type "dstimer -i"
  Sleep 1s
  Enter
  Sleep 1500ms
  Type "0"
  Sleep 400ms
  Type "0"
  Sleep 400ms
  Type "0"
  Sleep 400ms
  Type "0"
  Sleep 400ms
  Type "0"
  Sleep 400ms
  Type "7"
  Sleep 1s
  Enter
  Sleep 1s

  Set TypingSpeed 77ms

  Type "/home/linuxg/Musik/Super Survivor.flac"
  Sleep 1s
  Enter
  Sleep 9s
